### ISSUE TITLE
Null Reference Exception opening Preferences

### ISSUE THREAD

**Issue by deathau** [shellscape/Gmail-Notifier-Plus#138] opened 2016-08-15 00:29 UTC
After installing Gmail Notifier Plus 3.7, I tell it to open automatically, and I get the following error window. Also happens when I try to open Preferences from the jump list. I can't register an account and the app is useless to me at the moment.

Windows 10 Pro (Post anniversary update), 64-bit.

If you need any more information, let me know. I can see that some others have posted similar issues but weren't able to provide details.

Copied error details below:

[Window Title]
Gmail Notifier Plus Error

[Main Instruction]
An unhandled exception occurred:

[Content]
Error ID: 68de63db-bcbc-4826-a77b-3342bb735587

Object reference not set to an instance of an object.

[Expanded Information]

Server stack trace: 
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Shellscape.Remoting.RemotingSingleton.Run(String[] arguments)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Shellscape.Remoting.RemotingSingleton.Run(String[] arguments)
   at Shellscape.Program.CallRunningInstance(String[] arguments)

[V] See details  [OK]

[Footer]
Press CTL + C to copy this error to the clipboard.

**Comment by shellscape** [comment] 2016-08-15 13:46
hey there. thanks for taking the time to file the report. I haven't used windows in years, so I don't actively maintain the app. @jansokoly was the last person to actively maintain GNP, and his last commit was 2 years ago. I'd welcome a pull request to fix your error, but beyond that it may not get fixed.

**Comment by jansokoly** [comment] 2016-08-15 14:55
I'll look into it. I can confirm trying to open Preferences from the jump list results in the error described above.

**Comment by deathau** [comment] 2016-08-16 02:34
Thanks for taking a look into it. In case it helps and you haven't found out already, I downloaded the source and it looks like the problem is a resource from authui.dll doesn't exist anymore
[Preferences.cs L232](https://github.com/shellscape/Gmail-Notifier-Plus/blob/master/Application/Forms/Preferences.cs#L232). I guess it should just be a matter of finding a replacement and bundling it with the app?

**Comment by dmitry-lipetsk** [comment] 2016-09-28 10:30
Workaround: find the authui.dll [32bit, 10.0.10586.494] and copy it to "Gmail Notifier Plus" folder.

**Comment by shellscape** [comment] 2016-09-28 12:26
When I put that dialog together (back on Windows 7, when Windows 7 was newish) I tried to use as many core resources from Windows as possible. This was to avoid the mishmash of custom dialogs that nearly every Windows app at the time went with. Given that there's been two Windows versions since version 7, that dialog may need an update to get with the times. Not sure if bundling authui.dll with the app is a wise choice across windows versions. But that's a solid workaround in the mean time @dmitry-lipetsk, thanks.

**Comment by herringgas** [comment] 2016-11-18 17:50
I can also confirm that the fix @dmitry-lipetsk  worked for me as well. One difference in my case is used the version of authui.dll (32bit, 6.1.7601.23537) from a Windows 7 system and placed it in the "C:\Users\Owner\AppData\Local\Shellscape\Gmail Notifier Plus\Gmail folder. 

@jansokoly would this being something you would be willing to fix for a donation?

**Comment by jansokoly** [comment] 2016-12-10 14:18
This is now fixed in master and will be released as part of version 3.8.

**Comment by jansokoly** [comment] 2016-12-10 14:58
So, [3.8 is out](https://github.com/shellscape/Gmail-Notifier-Plus/releases/tag/v3.8). The built-in update mechanism will prompt you.
Let me know if it fixes the issue for you.

**Comment by shellscape** [comment] 2016-12-10 15:17
I'll update shellscape.org. Cheers

**Closed** 2016-12-11 18:59 UTC
