### ISSUE TITLE
Object reference not set to an instance of an object when trying to launch preferences

### ISSUE THREAD

**Issue by abrach** [shellscape/Gmail-Notifier-Plus#140] opened 2016-10-16 15:23 UTC
Running Windows 10 pro 32 bit
AMD FX-6300 8.0GB RAM NVIDIA GeoForce GTX 750 Ti
GNP version 3.7.0.0

[Window Title]
Gmail Notifier Plus Error

[Main Instruction]
An unhandled exception occurred:

[Content]
Error ID: 21d81dff-d784-4263-8af5-e98f7031a8e2

Object reference not set to an instance of an object.

[Expanded Information]

Server stack trace: 
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Shellscape.Remoting.RemotingSingleton.Run(String[] arguments)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Shellscape.Remoting.RemotingSingleton.Run(String[] arguments)
   at Shellscape.Program.CallRunningInstance(String[] arguments)

[^] Hide details  [OK]

[Footer]

**Comment by shellscape** [comment] 2016-10-16 15:28
duplicate of #138. please see that issue for comments.

**Closed by shellscape** 2016-10-16 15:28 UTC
