### ISSUE TITLE
2-step Verification Compatability

### ISSUE THREAD

**Issue by timcurran** [shellscape/Gmail-Notifier-Plus#143] opened 2017-07-07 23:19 UTC
Does not appear to be compatible with Google 2-step Verification. Would love to use it, if this feature is possible to add.

**Comment by pneuschwander** [comment] 2017-07-08 01:29
Maybe duplicate of #139

**Comment by shellscape** [comment] 2017-07-08 03:12
confirmed duplicate. the solution for this is in #139

**Closed as completed by shellscape** 2017-07-08 03:12 UTC
